import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  Pressable,
  TouchableOpacity,
} from 'react-native';

const services = [
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
  {id: '1', name: 'Web Development'},
  {id: '2', name: 'Mobile App Development'},
  {id: '3', name: 'UI/UX Design'},
  {id: '4', name: 'Cloud Services'},
];

const Service = ({navigation}) => {
  return (
    <View style={styles.container}>
      <Text style={styles.header}>Our Services</Text>
      <FlatList
        data={services}
        keyExtractor={item => item.id}
        renderItem={({item}) => (
          <TouchableOpacity
            onPress={() => {
              navigation.navigate('Profile');
            }}
            style={styles.serviceItem}>
            <Text style={styles.serviceText}>• {item.name}</Text>
          </TouchableOpacity>
        )}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
    padding: 20,
    paddingTop: 60,
  },
  header: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
    textAlign: 'center',
  },
  serviceItem: {
    backgroundColor: '#1f1f1f',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  serviceText: {
    color: '#ffffff',
    fontSize: 16,
  },
});

export default Service;
